exports.checkList = [
  { name: "Announce your engagement", status: false, category: "Preparation" },
  { name: "Choose your wedding party", status: false, category: "Preparation" },
  { name: "Outline your budget", status: false, category: "Preparation" },
  { name: "Estimate your guest count", status: false, category: "Preparation" },
  { name: "Finalise guest list", status: false, category: "Preparation" },
  {
    name: "Create your wedding website",
    status: false,
    category: "Preparation",
  },
  {
    name: "Hire a wedding planner (if you’d like to!)",
    status: false,
    category: "Preparation",
  },
  { name: "Find your dream venue", status: false, category: "Venue" },
  {
    name: "Book your registrar/Religious Minister",
    status: false,
    category: "Venue",
  },
  {
    name: "Order and send save the dates",
    status: false,
    category: "Invitations",
  },
  {
    name: "Find your photographer and videographer",
    status: false,
    category: "Photography",
  },
  { name: "Pick a wedding caterer", status: false, category: "Catering" },
  {
    name: "Find and buy your wedding dress",
    status: false,
    category: "Attire",
  },
  {
    name: "Schedule your engagement shoot",
    status: false,
    category: "Photography",
  },
  { name: "Source invitations", status: false, category: "Invitations" },
  {
    name: "Book your wedding entertainment",
    status: false,
    category: "Entertainment",
  },
  {
    name: "Choose your flowers and decorations",
    status: false,
    category: "Decorations",
  },
  {
    name: "Book your hair and make up artist",
    status: false,
    category: "Beauty",
  },
  { name: "Order your wedding cake", status: false, category: "Catering" },
  {
    name: "Arrange guest accommodation",
    status: false,
    category: "Accommodation",
  },
  { name: "Plan the ceremony", status: false, category: "Ceremony" },
  { name: "Choose your gift list", status: false, category: "Gifts" },
  { name: "Shop for shoes and accessories", status: false, category: "Attire" },
  { name: "Book your wedding transport", status: false, category: "Transport" },
  { name: "Book your honeymoon", status: false, category: "Honeymoon" },
  { name: "Pick bridesmaid dresses", status: false, category: "Attire" },
  {
    name: "Pick your groom’s and groomsmen attire",
    status: false,
    category: "Attire",
  },
  { name: "Buy your wedding rings", status: false, category: "Attire" },
  {
    name: "Book ceremony and reception music",
    status: false,
    category: "Music",
  },
  {
    name: "Choose colours and a theme",
    status: false,
    category: "Decorations",
  },
  {
    name: "Create your wedding day itinerary",
    status: false,
    category: "Planning",
  },
  { name: "Get your marriage license", status: false, category: "Legal" },
  { name: "Prepare speeches", status: false, category: "Speeches" },
  { name: "Create your table plan", status: false, category: "Planning" },
  {
    name: "Choose wedding favours and party gifts",
    status: false,
    category: "Decorations",
  },
  {
    name: "Design and order your seating plan and place cards",
    status: false,
    category: "Decorations",
  },
  {
    name: "Purchase thank you gifts for the wedding party",
    status: false,
    category: "Gifts",
  },
  {
    name: "Enjoy your stag and hen parties",
    status: false,
    category: "Celebration",
  },
  { name: "Final checks", status: false, category: "Planning" },
  { name: "Relax before the big day!", status: false, category: "Pre-Wedding" },
];
